!IF 0

Copyright

Module Name:
	makefile.
!ENDIF

# @@ COPYRIGHT HERE
# @@ roadmap :: The Makefile the product-wide header files

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!endif # NTMAKEENV
