!IF 0

Copyright (C) Microsoft Coorporation, 1999 - 1999

Module Name:
	makefile.
!ENDIF

# @@ COPYRIGHT HERE
# @@ ROADMAP :: The Makefile the product-wide header files

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!endif # NTMAKEENV
